# 应用端口
server:
  port: 10086
spring:
  application:
    # 应用名称
    name: digitaltwins-testing

# eureka 配置
eureka:
  client:
    serviceUrl:
      defaultZone: http://root:123@localhost:8761/eureka

logging:
  level:
    root: INFO
